import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from "@/provider/AuthContext";
import ReduxProvider from "@/redux/ReduxProvider";
import Header from "@/components/header/Header";

import 'rsuite/dist/rsuite-no-reset.min.css';
import { CustomProvider } from 'rsuite';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthProvider>
          <ReduxProvider>
            <CustomProvider>
              {/* <button className='scroll-top scroll-to-target' onClick={() => handleTopScreen()}>
              <FontAwesomeIcon icon={faAngleUp} />
            </button> */}
              {/* Include the header */}
              {/* <Header /> */}
              <section className='container-fluid p-0 m-0'>
                {/* <Menu /> */}
                {/* <main className='fix' style={{ marginLeft: '285px' }}> */}
                <main className='fix'>
                  {children}
                </main>
              </section>
              {/* <CookieConsent /> */}
            </CustomProvider>
          </ReduxProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
